name: Deploy to Azure VM

on:
  push:
    branches:
      - skywalking-azure

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: true
        tags: keshavimperial/skywalking:latest

    - name: Deploy to Azure VM
      env:
        SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
        VM_IP: ${{ secrets.VM_IP }}
        VM_USER: ${{ secrets.VM_USER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        eval $(ssh-agent)
        ssh-add ~/.ssh/id_ed25519
        ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP << 'EOF'
          cd ~/skywalking/docker
          docker-compose --profile elasticsearch up -d
        EOF

