name: Deploy to Azure VM

on:
  push:
    branches:
      - main
      - skywalking-azure

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Deploy to Azure VM
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VM_IP: ${{ secrets.VM_IP }}
        VM_USER: ${{ secrets.VM_USER }}
      run: |
        # Create .ssh directory
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        # Write SSH private key and set permissions
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        # Add the SSH key to the ssh-agent
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519
        ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP << 'EOF'
          cd /skywalking/docker  # Navigate to the docker folder on your VM
          docker-compose --profile elasticsearch down  # Stop any existing containers
          docker-compose --profile elasticsearch pull  # Pull latest images
          docker-compose --profile elasticsearch up -d  # Start the containers
        EOF

