name: Deploy to Azure VM

on:
  push:
    branches:
      - skywalking-azure

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Deploy to Azure VM
      env:
        SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
        VM_IP: ${{ secrets.VM_IP }}
        VM_USER: ${{ secrets.VM_USER }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode | ssh-add -

        # Connect to the VM and execute commands
        ssh -vvv -o StrictHostKeyChecking=no -t $VM_USER@$VM_IP << 'EOF'
          cd ~/skywalking/docker
          docker-compose --profile elasticsearch up -d
        EOF

