name: Publish E2E service images

on:
  push:
    branches:
      - skywalking-azure

env:
  SKIP_TEST: true
  HUB: ghcr.io/keshav8s/skywalking

jobs:
  build:
    if: github.repository == 'Keshav8s/skywalking'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 90
    env:
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push images
        run: make -C test build.e2e-service docker.push-e2e-service
        env:
          HUB: ${{ env.HUB }}
          TAG: ${{ env.TAG }}

      - name: Push the image to your registry
        run: |
          docker build -t ${{ env.HUB }}/skywalking-ui:latest -f ~/docker/ui/Dockerfile
          docker push ${{ env.HUB }}/skywalking-ui:latest

          docker build -t ${{ env.HUB }}/skywalking-oap:latest -f ~/docker/oap/Dockerfile
          docker push ${{ env.HUB }}/skywalking-oap:latest

          #docker build -t docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.2 -f ~/
